Feature/refactor
f-lab-edu/auto-summary pull request #11
Opened 2024-09-16 16:17 UTC by sksowk156

[변경 사항]
- Repository 이름들을 Repository에서 다루는 데이터 클래스에 맞게 ChatHistoryRepository, ChatSummaryRepository로 변경했습니다.
- 대화가 진행되는 동안 실시간으로 ChatHistory에 저장하도록 구현해 ViewModel에서 사용하던 불필요한 UI 요청 및 응답 데이터 클래스를 제거했습니다.

2024-09-17 13:01 UTC, jerry-f-lab commented
PR 타이틀을 적절하게 바꿔 적어주세요. 지난 주 목표였던 CI/CD는 해보셨나요?

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatCompletionRepositoryImpl.kt
> +        withContext(Dispatchers.IO) {
여러번 반복했던 것 같은데, 여기에 `withContext()`가 있어야 하는 이유가 있을까요?

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatCompletionRepositoryImpl.kt
> +                    .extractContent()
혹시 길게 길게 dot chain을 연결했다고 뿌듯해하고 계시진 않으신가요?
코드 리더를 위한 배려가 충분히 되었다고 생각이 되시나요?

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatCompletionRepositoryImpl.kt
> +        this.choices
불필요한 `this.`입니다.

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/data/repository/ChatHistoryRepository.kt
> +    suspend fun addOrUpdateChatHistory(chatHistory: ChatHistory): ChatHistory?
반환되는 `ChatHistory?`는 무엇을 의미하나요?
Primary sentence를 적어 줄 수 있으시겠어요?

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatHistoryRepositoryImpl.kt
> +                }
혹시 여기서도 길게 dot chain을 완성했다고 뿌듯해하고 계시진 않으신가요? 코드 리더를 위한 충분한 배려가 있었나요?

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatHistoryRepositoryImpl.kt
> +            messages = chatHistory
```suggestion
            messages = chatHistory.messages + ChatHistory.Message(content=latestMessage,isUser=isUser)
```
이면 충분할 것 같습니다.

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatHistoryRepositoryImpl.kt
> +    }
모든 컨버터를 이렇게 만들어야 한다고 누가 가르쳐주시던가요? 혹시 특별한 이유가 있나요?

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatCompletionRepositoryImpl.kt
> +            .content
모든 컨버터를 이렇게 만들어야 한다고 누가 가르쳐주시던가요? 왜 이렇게 하시는 걸까요?

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatSummaryRepositoryImpl.kt
> +            .toList()
대단히 뿌듯해하고 계실 것 같은데, 뿌듯해하지 않으셔야 합니다.
```kotlin
val promptizedSummaries = chatSummaries.mapTo(mutableListOf()) {
  "summaries:${convertChatSummaryToJson(it)}"
}
promptizedSummaries += """
...
"""
return promptizedSummaries
```
마지막의 `toList()`는 불필요합니다.

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/network/retrofit/RetrofitGptApiHolder.kt
> +                    }
Nice

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/core/network/retrofit/RetrofitGptApiHolder.kt
> +                            .addHeader("Accept", "application/json")
```suggestion
                            .addHeader("Content-Type", "application/json; charset=utf-8")
                            .addHeader("Accept", "application/json; charset=utf-8")
```
utf-8을 붙여주시는게 좋습니다. 왜 인지는 스스로 찾아보세요.

2024-09-17 13:20 UTC, jerry-f-lab commented on app/src/main/java/com/sjh/autosummary/feature/main/MainScreen.kt
> +                        if (message.isUser) {
A message is a user.
올바른 영어로 읽히나요? 올바른 영어가 아니라면 usage 설계(즉, 인터페이스 설계)가 잘못되었다는 증명입니다.

2024-09-18 07:10 UTC, sksowk156 commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatCompletionRepositoryImpl.kt
> +        withContext(Dispatchers.IO) {
앗 맞습니다. 계속 코드를 보다 보니 익숙해져서 인지하지 못했던 것 같습니다.

2024-09-18 07:14 UTC, sksowk156 commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatCompletionRepositoryImpl.kt
> +                    .extractContent()
다시 읽어보니 createChatCompletion에서 extractContent했을 때 assistantMessage 가 된다는 것이 이상한 것 같습니다. 나눠서 작성하겠습니다!

2024-09-18 07:23 UTC, sksowk156 commented on app/src/main/java/com/sjh/autosummary/core/data/repository/ChatHistoryRepository.kt
> +    suspend fun addOrUpdateChatHistory(chatHistory: ChatHistory): ChatHistory?
아 이 부분은 제가 잘못 변경한 부분인 것 같습니다. 원래는 addOrUpdateChatHistory으로 chathistory의 messages를 업데이트 하는 로직을 넣으려고 했는데, 기존의 메서드 역할과 많이 달라지는 것 같아서 , updateChatHistoryMessages라는 메서드로 따로 기능을 구현했습니다. 그 과정에서 addOrUpdateChatHistory의 반환 값을 원래대로 돌려놓는걸 깜빡했던 것 같습니다. 다시 수정해두겠습니다!

2024-09-18 07:26 UTC, sksowk156 commented on app/src/main/java/com/sjh/autosummary/core/data/repository/impl/ChatHistoryRepositoryImpl.kt
> +    }
특별한 이유는 없었습니다! 변환할 때 코드를 한 줄로 표현할 수 있다는 점이 깔끔해 보여서 사용했던 것 같습니다. 다른 곳에서 또 쓰이는 것이 아니라면 내부 로직에 그대로 사용할 수 있도록 수정하겠습니다!

2024-09-18 07:27 UTC, sksowk156 commented on app/src/main/java/com/sjh/autosummary/core/network/retrofit/RetrofitGptApiHolder.kt
> +                            .addHeader("Accept", "application/json")
넵! 조사해보겠습니다!

2024-09-18 07:31 UTC, sksowk156 commented on app/src/main/java/com/sjh/autosummary/feature/main/MainScreen.kt
> +                        if (message.isUser) {
아! 변수를 감싸는 클래스명을 고려해 변수명을 작성할 수 있도록 하겠습니다! 감사합니다!

2024-09-18 14:46 UTC, jerry-f-lab submitted a review, later dismissed

2024-09-22 02:49 UTC, jerry-f-lab requested changes
이상한 파일들이 추가되었네요.

2024-09-25 14:31 UTC, jerry-f-lab commented
@sksowk156 apk & profile 결과 파일도 삭제해주세요.

2024-09-25 15:41 UTC, jerry-f-lab approved these changes

2024-09-25 16:42 UTC, merged

2024-09-25 16:43 UTC, sksowk156 commented
지금까지 제리님의 피드백을 받을 수 있어 정말 영광이었습니다. 
진심으로 감사드립니다!